name = "tiff"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
STORAGE_READ_SOURCE = "kv"
STORAGE_DUAL_WRITE = "false"
D1_CANARY_EMAILS = ""

[[kv_namespaces]]
binding = "TIFF_KV"
id = "e02956f78fa64637ad72b37805219bf1"

[[r2_buckets]]
binding = "TIFF_ATTACHMENTS"
bucket_name = "tiff-attachments"
preview_bucket_name = "tiff-attachments"

[[d1_databases]]
binding = "TIFF_DB"
database_name = "tiff"
database_id = "7f14991c-0756-4f35-8124-ca64d9012a85"
migrations_dir = "migrations"
